nodeLinker: node-modules

plugins:
  # This is to solve the problem where prepare and postinstall is not available in yarn 3.
  # Refs: https://github.com/yarnpkg/yarn/issues/5476#issuecomment-1713264396
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.5.0/bundles/@yarnpkg/plugin-after-install.js'

afterInstall: yarn afterInstall

yarnPath: .yarn/releases/yarn-3.7.0.cjs
